//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKiSu_ThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuMuon
    {
        public string MaChiTiet { get; set; }
        public Nullable<int> ID_PhieuMuon { get; set; }
        public string MaTL { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTraSach { get; set; }
    
        public virtual BanSaoTaiLieu BanSaoTaiLieu { get; set; }
        public virtual PhieuMuon PhieuMuon { get; set; }
    }
}
