//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKiSu_ThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocGia()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
        }
    
        public string MaDocGia { get; set; }
        public Nullable<int> ID_DoiTuong { get; set; }
        public string TenDocGia { get; set; }
        public string DonVi { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string CCCD { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<int> KhoaHoc { get; set; }
        public Nullable<long> SoDu { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DoiTuongDocGia DoiTuongDocGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
        public virtual TheThuVien TheThuVien { get; set; }
    }
}
