//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKiSu_ThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoiTuongDocGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoiTuongDocGia()
        {
            this.DocGias = new HashSet<DocGia>();
        }
    
        public int ID_DoiTuong { get; set; }
        public string TenDoiTuong { get; set; }
        public Nullable<int> SoLuongTaiLieu { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public Nullable<int> SoLanGiaHan { get; set; }
        public Nullable<int> SoNgayGiaHan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocGia> DocGias { get; set; }
    }
}
