//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKiSu_ThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeSach
    {
        public int ID_KS { get; set; }
        public string MaKe { get; set; }
        public Nullable<int> Tang { get; set; }
    
        public virtual Tang Tang1 { get; set; }
    }
}
