//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKiSu_ThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaXuatBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaXuatBan()
        {
            this.PhienBanTaiLieux = new HashSet<PhienBanTaiLieu>();
        }
    
        public int ID_NXB { get; set; }
        public string MaNhaXuatBan { get; set; }
        public string TenNXB { get; set; }
        public string DiaChi { get; set; }
        public string QuocGia { get; set; }
        public string DienThoai { get; set; }
        public string NguoiDaiDien { get; set; }
        public string Email { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhienBanTaiLieu> PhienBanTaiLieux { get; set; }
    }
}
