//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKiSu_ThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public string MaNhomND { get; set; }
        public int ID_ChucNang { get; set; }
        public Nullable<bool> CoQuyen { get; set; }
    
        public virtual ChucNangCon ChucNangCon { get; set; }
        public virtual NhomNguoiDung NhomNguoiDung { get; set; }
    }
}
