//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKiSu_ThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhienBanTaiLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhienBanTaiLieu()
        {
            this.BanSaoTaiLieux = new HashSet<BanSaoTaiLieu>();
        }
    
        public int ID_PhienBan { get; set; }
        public Nullable<int> ID_TaiLieu { get; set; }
        public Nullable<int> ID_NhaXuatBan { get; set; }
        public Nullable<int> NamXuatBan { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public Nullable<int> ChieuRong { get; set; }
        public Nullable<int> ChieuCao { get; set; }
        public string AnhBia { get; set; }
        public string AnhMobile { get; set; }
        public string MoTa { get; set; }
        public string ISBN_ISSN { get; set; }
        public Nullable<int> GiaTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanSaoTaiLieu> BanSaoTaiLieux { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual TaiLieu TaiLieu { get; set; }
    }
}
