//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKiSu_ThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanNoiBo
    {
        public int ID_NV { get; set; }
        public string MatKhau { get; set; }
        public string TrangThai { get; set; }
        public string MaNhom { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhomNguoiDung NhomNguoiDung { get; set; }
    }
}
