//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKiSu_ThuVien.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienLai
    {
        public int id_bien_lai { get; set; }
        public int id_doc_gia { get; set; }
        public int id_sach { get; set; }
        public int id_ld { get; set; }
        public Nullable<System.DateTime> ngay_lap { get; set; }
    
        public virtual DocGia DocGia { get; set; }
        public virtual LyDo LyDo { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
