//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKiSu_ThuVien.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocGia()
        {
            this.BienLais = new HashSet<BienLai>();
            this.PhieuMuons = new HashSet<PhieuMuon>();
        }
    
        public int id_doc_gia { get; set; }
        public Nullable<int> id_khoa_hoc { get; set; }
        public string MSSV { get; set; }
        public string ho_ten_doc_gia { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public string noi_sinh { get; set; }
        public string lop { get; set; }
        public Nullable<int> nam_hoc { get; set; }
        public Nullable<System.DateTime> ngay_muon { get; set; }
        public Nullable<System.DateTime> ngay_tra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienLai> BienLais { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
    }
}
