//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKiSu_ThuVien.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMuon
    {
        public int id_phieu_muon { get; set; }
        public int id_doc_gia { get; set; }
        public int id_sach { get; set; }
        public Nullable<System.DateTime> ngay_muon { get; set; }
        public Nullable<System.DateTime> ngay_tra { get; set; }
        public Nullable<double> tien_phat_sinh { get; set; }
    
        public virtual DocGia DocGia { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
