//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKiSu_ThuVien.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKe
    {
        public int id_thong_ke { get; set; }
        public string ten_thong_ke { get; set; }
        public Nullable<int> id_nhan_vien { get; set; }
        public Nullable<System.DateTime> ngay_thong_ke { get; set; }
        public Nullable<int> id_sach { get; set; }
        public Nullable<int> so_luong { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
